# Generated by Django 6.0.6 on 2026-07-07 08:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='works/files/'),
        ),
        migrations.AddField(
            model_name='work',
            name='content_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='work',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='media_type',
            field=models.CharField(choices=[('image', '图片'), ('pdf', 'PDF'), ('video', '视频'), ('link', '链接')], default='image', max_length=20),
        ),
        migrations.AddField(
            model_name='work',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ChunkedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('media_type', models.CharField(choices=[('image', '图片'), ('pdf', 'PDF'), ('video', '视频'), ('link', '链接')], max_length=20)),
                ('total_size', models.PositiveBigIntegerField()),
                ('total_chunks', models.PositiveIntegerField()),
                ('uploaded_chunks', models.JSONField(default=list)),
                ('file', models.FileField(blank=True, null=True, upload_to='works/files/')),
                ('status', models.CharField(choices=[('uploading', '上传中'), ('completed', '已完成')], default='uploading', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunked_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
