# Generated by Django 6.0.6 on 2026-07-15 02:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def convert_existing_codes_to_four_digits(apps, schema_editor):
    AttendanceSession = apps.get_model('api', 'AttendanceSession')
    sessions_by_date = {}
    for session in AttendanceSession.objects.order_by('date', 'id'):
        sessions_by_date.setdefault(session.date, []).append(session)

    for sessions in sessions_by_date.values():
        if len(sessions) > 10000:
            raise RuntimeError('同一天的签到场次超过 4 位签到码容量')

        # 先改成不会与数字签到码冲突的临时值，避免逐条更新时触发唯一约束冲突。
        for index, session in enumerate(sessions):
            session.code = f'X{index:04d}'
            session.save(update_fields=['code'])

        used_codes = set()
        for session in sessions:
            candidate = (session.pk * 7919) % 10000
            while f'{candidate:04d}' in used_codes:
                candidate = (candidate + 1) % 10000
            session.code = f'{candidate:04d}'
            session.save(update_fields=['code'])
            used_codes.add(session.code)


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('api', '0009_attendancesession_attendancerecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(convert_existing_codes_to_four_digits, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='attendancesession',
            name='code',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', '签到码必须是 4 位数字')]),
        ),
        migrations.CreateModel(
            name='AttendanceAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'student'), name='unique_student_attendance_attempt')],
            },
        ),
    ]
