# Generated by Django 6.0.6 on 2026-07-16 06:26

import api.course_files
import api.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_attendancesession_code_attendanceattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mind_map',
            field=models.FileField(blank=True, null=True, storage=api.storage.ProtectedCourseStorage(), upload_to=api.course_files.course_mind_map_upload_to, validators=[api.course_files.validate_course_mind_map_file]),
        ),
        migrations.AddField(
            model_name='course',
            name='mind_map_content_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='course',
            name='mind_map_file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='mind_map_original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=api.storage.ProtectedCourseStorage(), upload_to=api.course_files.course_resource_upload_to, validators=[api.course_files.validate_course_resource_file])),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('file_size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='api.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_course_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
