# Generated by Django 6.0.6 on 2026-07-17 02:11

import api.storage
import api.work_files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_update_2026_training_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkedupload',
            name='protected_file',
            field=models.FileField(blank=True, null=True, storage=api.storage.ProtectedCourseStorage(), upload_to=api.work_files.protected_work_html_upload_to),
        ),
        migrations.AddField(
            model_name='work',
            name='protected_attachment',
            field=models.FileField(blank=True, null=True, storage=api.storage.ProtectedCourseStorage(), upload_to=api.work_files.protected_work_html_upload_to),
        ),
        migrations.AlterField(
            model_name='chunkedupload',
            name='media_type',
            field=models.CharField(choices=[('image', '图片'), ('pdf', 'PDF'), ('video', '视频'), ('html', 'HTML'), ('link', '链接')], max_length=20),
        ),
        migrations.AlterField(
            model_name='work',
            name='media_type',
            field=models.CharField(choices=[('image', '图片'), ('pdf', 'PDF'), ('video', '视频'), ('html', 'HTML'), ('link', '链接')], default='image', max_length=20),
        ),
    ]
