# Generated by Django 6.0.6 on 2026-07-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_work_html_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='training_group',
            field=models.CharField(blank=True, choices=[('1', '第1组'), ('2', '第2组'), ('3', '第3组'), ('4', '第4组'), ('5', '第5组'), ('6', '第6组')], max_length=1),
        ),
    ]
