"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_local_environment(path):
    if not path.exists():
        return
    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


load_local_environment(BASE_DIR.parent / '.env.local')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
ENVIRONMENT = os.environ.get('DJANGO_ENV', 'development').lower()
IS_PRODUCTION = ENVIRONMENT == 'production'
DEV_SECRET_KEY = 'dev-only-change-me-please-use-an-environment-key'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', DEV_SECRET_KEY)
if IS_PRODUCTION and (SECRET_KEY == DEV_SECRET_KEY or len(SECRET_KEY) < 32):
    raise ImproperlyConfigured('生产环境必须配置至少 32 位的 DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'false' if IS_PRODUCTION else 'true').lower() == 'true'
if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured('生产环境不能开启 DJANGO_DEBUG')

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_ENGINE = os.environ.get('DJANGO_DB_ENGINE', 'django.db.backends.sqlite3')
DATABASES = {
    'default': {
        'ENGINE': DB_ENGINE,
        'NAME': os.environ.get('DJANGO_DB_NAME', str(BASE_DIR / 'db.sqlite3')),
    }
}
if DB_ENGINE != 'django.db.backends.sqlite3':
    DATABASES['default'].update({
        'USER': os.environ.get('DJANGO_DB_USER', ''),
        'PASSWORD': os.environ.get('DJANGO_DB_PASSWORD', ''),
        'HOST': os.environ.get('DJANGO_DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DJANGO_DB_PORT', '5432'),
        'CONN_MAX_AGE': int(os.environ.get('DJANGO_DB_CONN_MAX_AGE', '60' if IS_PRODUCTION else '0')),
    })


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
COURSE_MATERIAL_ROOT = Path(os.environ.get('COURSE_MATERIAL_ROOT', BASE_DIR / 'protected_course_files'))
COURSE_MIND_MAP_MAX_SIZE = int(os.environ.get('COURSE_MIND_MAP_MAX_SIZE', 10 * 1024 * 1024))
COURSE_MIND_MAP_MAX_PIXELS = int(os.environ.get('COURSE_MIND_MAP_MAX_PIXELS', 40_000_000))
COURSE_RESOURCE_MAX_SIZE = int(os.environ.get('COURSE_RESOURCE_MAX_SIZE', 100 * 1024 * 1024))
COURSE_RESOURCE_MAX_FILES = int(os.environ.get('COURSE_RESOURCE_MAX_FILES', 10))
COURSE_MATERIAL_MAX_REQUEST_SIZE = int(os.environ.get('COURSE_MATERIAL_MAX_REQUEST_SIZE', 200 * 1024 * 1024))
COURSE_PPTX_MAX_UNCOMPRESSED_SIZE = int(
    os.environ.get('COURSE_PPTX_MAX_UNCOMPRESSED_SIZE', 500 * 1024 * 1024)
)
COURSE_PPTX_MAX_MEMBERS = int(os.environ.get('COURSE_PPTX_MAX_MEMBERS', 5000))
COURSE_MATERIAL_USE_X_ACCEL = os.environ.get(
    'COURSE_MATERIAL_USE_X_ACCEL',
    'true' if IS_PRODUCTION else 'false',
).lower() == 'true'
COURSE_MATERIAL_X_ACCEL_PREFIX = os.environ.get(
    'COURSE_MATERIAL_X_ACCEL_PREFIX',
    '/_protected_course_files/',
)
WORK_MAX_UPLOAD_SIZE = int(os.environ.get('WORK_MAX_UPLOAD_SIZE', 500 * 1024 * 1024))
WORK_UPLOAD_CHUNK_DIR = MEDIA_ROOT / 'upload_chunks'
WORK_MAX_UPLOAD_CHUNK_SIZE = int(os.environ.get('WORK_MAX_UPLOAD_CHUNK_SIZE', 8 * 1024 * 1024))
WORK_MAX_UPLOAD_CHUNKS = int(os.environ.get('WORK_MAX_UPLOAD_CHUNKS', 1000))
WORK_MAX_ACTIVE_UPLOADS = int(os.environ.get('WORK_MAX_ACTIVE_UPLOADS', 5))
WORK_MAX_PENDING_UPLOAD_BYTES = int(os.environ.get('WORK_MAX_PENDING_UPLOAD_BYTES', 1024 * 1024 * 1024))
WORK_UPLOAD_SESSION_TTL_HOURS = int(os.environ.get('WORK_UPLOAD_SESSION_TTL_HOURS', 24))
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('DATA_UPLOAD_MAX_MEMORY_SIZE', 20 * 1024 * 1024))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('FILE_UPLOAD_MAX_MEMORY_SIZE', 10 * 1024 * 1024))

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'DJANGO_CORS_ALLOWED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173,http://localhost:8000,http://127.0.0.1:8000',
    ).split(',')
    if origin.strip()
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.environ.get('DRF_ANON_THROTTLE_RATE', '60/min'),
        'user': os.environ.get('DRF_USER_THROTTLE_RATE', '300/min'),
        'login': os.environ.get('DRF_LOGIN_THROTTLE_RATE', '10/min'),
        'upload': os.environ.get('DRF_UPLOAD_THROTTLE_RATE', '180/min'),
        'search': os.environ.get('DRF_SEARCH_THROTTLE_RATE', '60/min'),
        'attendance': os.environ.get('DRF_ATTENDANCE_THROTTLE_RATE', '10/min'),
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = IS_PRODUCTION
SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SECURE = IS_PRODUCTION
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '31536000' if IS_PRODUCTION else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = IS_PRODUCTION
SECURE_HSTS_PRELOAD = IS_PRODUCTION
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
